# This is a basic workflow to help you get started with Actions

name: Jira to Teams Notifier

on:
  schedule:
    # Ejecutar cada 5 minutos
    - cron: "*/1 * * * *"
  workflow_dispatch:  # Para lanzarlo manualmente también

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          FILTER_ID:  ${{ secrets.FILTER_ID }}
        run: python script.py
